name: github checkout action

on: [push]

jobs:
  checkout-a-repo:
    runs-on: ubuntu-latest
    steps:
      - name: ls before checkout
        run: |
          ls -a -R
          echo "${{ github.repository }}"
          echo "${{ github.token }}"
      - name: clone a repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
      - name: ls after checkout
        run: ls -a -R