name: matrix

on:
  push:

jobs: 
  node-version:
    runs-on: ubuntu-latest
    steps:
    - name: get node version before node-setup action
      run: |
        node -v
        npm -v
    - uses: actions/setup-node@v1
      with:
        node-version: 6
    - name: get node version after node-setup action
      run: |
        node -v
        npm -v